### ISSUE TITLE
Deleting on dev server

### ISSUE THREAD

**Issue by S1SYPHOS** [flokosiol/kirby-translations#10]
Hey there,
love the new sync option. Since v0.5 I now get this on my PHP dev server when trying to sync / delete a translation:

```
Not Found
The requested resource /panel/plugin.translations/fr/shop was not found on this server.
```

// Edit: Everything's working fine live by the way.

**Comment by flokosiol** [comment]
Thanks for reporting. Unfortunately I can't reproduce this issue. Any ideas what could be the difference between your live and dev server (PHP version, server config, ...)?

**Comment by flokosiol** [comment]
One more idea, @S1SYPHOS: Could you please check if all plugin files are up to date on the dev server. Especially the [main plugin file](https://github.com/flokosiol/kirby-translations/blob/master/translations.php) `site/plugins/translations/translations.php`. This is where the (new) routes are defined.

**Comment by S1SYPHOS** [comment]
Latest pull was commit 661eae7a37425f93826299e2a0e9485985f235b7 (README.md change), main plugin file is still [v0.5](https://github.com/flokosiol/kirby-translations/releases/tag/v0.5)!

**Comment by pqml** [comment]
Same issue using php v7.0.15 built-in server on OSX

**Comment by pqml** [comment]
I found the error! 

Dots in `plugin.translations` and `plugin.translations.update` are the problem.

The PHP built-in server doesn't use Apache so you can't rely on a htaccess files, and it seems to not be able to resolve url with dots itself.  

For instance, replacing `plugin.translations` by `plugin-translations` and `plugin.translations.update` by `plugin-translations-update` seems to fix the issue. But I don't know if it's the best alternative url though?

**Comment by flokosiol** [comment]
Great. Since the url is only used internally, it doesn't really matter what it looks like. I will change it for the next release. Thanks for checking that out!

**Comment by S1SYPHOS** [comment]
I'll be happy testing it 👍

**Comment by flokosiol** [comment]
Alright. I changed the urls and tested it successfully with OSX built in php server. 
Would be awesome if someone else could check it. Thanks in advance.

**Please use the `develop` branch:**
https://github.com/flokosiol/kirby-translations/tree/develop

**Comment by S1SYPHOS** [comment]
works 👍

**Comment by flokosiol** [comment]
Thanks for your support, guys.

**Comment by S1SYPHOS** [comment]
Thanks for this plugin.

Without plugins like this one, I wouldn't reach out to clients, suggesting to use Kirby at all (moreover: pay for it). I love your work.
