### ISSUE TITLE
Switch languages not working - Kirby 2.5.8

### ISSUE THREAD

**Issue by illycz** [flokosiol/kirby-translations#11]
After upgrade, languages switcher not working.
It look that Kirby change ```edit?language=en``` to ```edit?_language=en```

Here is PR: https://github.com/getkirby/panel/commit/8781a9947ecaca422739ef9331345a0c4910eda3

Do you plan update your plugin?

Thanks

**Comment by flokosiol** [comment]
Thanks for the info. I will check this as soon as possible and try to find a way to support the old and the new kirby version.

As a quick fix you could adjust the `href` at [this line](https://github.com/flokosiol/kirby-translations/blob/master/fields/translations/template.php#L4) in `fields/translations/template.php`

**Comment by flokosiol** [comment]
I fixed this issue in the [develop](https://github.com/flokosiol/kirby-translations/tree/develop) branch. Would be awesome, if you could check it, @illycz.

**Comment by illycz** [comment]
Yes, it's working now.

Thanks!
