### ISSUE TITLE
Translate the "Translation is up to date" label

### ISSUE THREAD

**Issue by ghost** [flokosiol/kirby-translations#12]
Hello, I would like to ask if there is a way to translate the checkbox label? When I set 

`l::set('translations.uptodate.text', 'Übersetzung ist aktuell')` 

in my language files, it does not do the trick. Is multilingual support build in the current version? 

If not I would like to work on a PR that adds this feature, based on Kirby Status plugin implementation.

Link: https://forum.getkirby.com/t/translating-panel-field-options-of-plugins/10720/2

Update: I have a PR ready that adds this feature: #13

**Comment by flokosiol** [comment]
See PR #13 …
