### ISSUE TITLE
Latest update breaks the plugin

### ISSUE THREAD

**Issue by EdwardLecock** [flokosiol/kirby-translations#14]
Please be more careful when merging pull requests. v0.8 has some breaking changes/bugs that aren't documented. I can't save translated pages any more, only the default language. Reverting to v0.7 fixed the issue for me

**Comment by flokosiol** [comment]
Thanks for reporting. I will have a look at it as soon as possible. Sorry for the inconvenience.

**Comment by flokosiol** [comment]
I re-checked v0.8, but for me everything works. I tested it with Kirby 2.5.8 and the latest Kirby 2.5.12 – both on PHP 7.1.10.

@EdwardLecock Would be great if you could provide some more details of your environment (Kirby version, PHP version and maybe an error message?). Thanks in advance.

**Comment by EdwardLecock** [comment]
I get the following error:
`Too few arguments to function translationsField::translate(), 0 passed in /Users/EL/Documents/Workspace/obi-cms/www/panel/app/src/panel/form.php on line 126 and exactly 1 expected`

Tested on Kirby version 2.5.10 and 2.5.12. Both on PHP 7.1.12

**Comment by pqml** [comment]
Same here

**Comment by pqml** [comment]
Made a PR for this one
https://github.com/flokosiol/kirby-translations/pull/15
