### ISSUE TITLE
Porting to K3

### ISSUE THREAD

**Issue by gfxdude-dus** [flokosiol/kirby-translations#16]
Hey Flo, Do you have any plans to port this little gem to k3? :D

**Comment by flokosiol** [comment]
Would love to … but at the moment I have almost no spare time fort this project … sorry 😞 

@sylvainjule already asked, maybe he will go for it?!

… and thanks for the "little gem"  ❤️ 😂

**Comment by gfxdude-dus** [comment]
you're welcome 😂
come on guys! i'll pay for the beer! this tittle helper is a musthave for sites with several editors!

**Comment by sylvainjule** [comment]
I'd love to have it for K3, but also have very little plugin-fun-time at the moment... 😕

**Comment by flokosiol** [comment]
Maybe we should start with a "light" version, which only checks if a translated .txt is available and switches the backend language on click … and then add some other features from K2 later?!

I'll check that possibility, @gfxdude-dus!

**Comment by gfxdude-dus** [comment]
yay! awesome! thanks a lot!

**Comment by flokosiol** [comment]
FYI: Just started with a first draft for Kirby3 😉 

<img width="1336" alt="kirby3-translations-draft" src="https://user-images.githubusercontent.com/11918336/52527555-aa148c00-2cca-11e9-86cf-142d41327d6f.png">

Still some problems to solve until the first basic version will be finished, but I'm quite optimistic to get it up and running one day 😜

**Comment by gfxdude-dus** [comment]
Thats fantastic! Lookin forward to use it some day ;) 
If you need a helping hand in some case, give me a hint!
Where i have to send the beer cans to?

**Comment by flokosiol** [comment]
Here we go: https://github.com/flokosiol/kirby-translations/tree/kirby3

@gfxdude-dus Would be great if you could test this basic version and give me some feedback. Please notice that there are some known issues listed in the README and the plugin can be installed only by downloading the ZIP at the moment.

> Where i have to send the beer cans to?

😂 I will be in DUS for [btconf](https://beyondtellerrand.com/) in May – let's meet in person.

**Comment by gfxdude-dus** [comment]
🥳you're freakin fast buddy! thanks!
im totally busy this week, but give it a try on the weekend for sure.
nice with the btconf! im not there by my own, i guess - but if theres a chance to meet for a beer, lets do it! fortunately we have the best beer in the country. lucky you! 🍻

**Comment by flokosiol** [comment]
Damn. I totally forgot to ping you again, before I went to DUS. 
Nevertheless I had sufficient alt beer 🍻 😂

**Comment by janstieler** [comment]
Hi @flokosiol ,
will you finish this kirby 3 port some times so that it is working also in production?

Best

**Comment by flokosiol** [comment]
Thanks for the reminder. Since it's been a while I have to take a closer look at it again. Thanks for your patience.

**Comment by MaluNoPeleke** [comment]
I would also be interested in it. Any update would be appreciated :)
Maybe @nilshoerrmann could support?

**Comment by illycz** [comment]
Port it please :)

**Comment by flokosiol** [comment]
Here's a short update from my side … 

I tried several times but can't get the plugin work properly as a field in K3 so far. This is necessary to store if the language is up to date or not.

Currently, you can check out the [kirby3(]https://github.com/flokosiol/kirby-translations/tree/kirby3) branch to use it as a section with the possibility to delete a language and/or to revert its content to the default language. But the **up to date** feature ist still missing. Damn. 😢

**Comment by flokosiol** [comment]
I finally launched the limited version (without the **up to date** feature) for Kirby 3. Thanks to @Daandelange this includes Kirby 3.6.
