### ISSUE TITLE
Page not found error when using the language buttons to switch edit language

### ISSUE THREAD

**Issue by texnixe** [flokosiol/kirby-translations#4]

**Comment by flokosiol** [comment]
Thanks for reporting. I'll have a look at this as soon as possible. 

I assume that you are using the master branch. The develop branch may break from time to time, because I also push my "work in progress".

**Comment by texnixe** [comment]
I tested this with both the master and the dev branches.

**Comment by flokosiol** [comment]
I could reproduce the issue, though my default test environment still works fine so far!? But I did a fresh langkit installation and the error occurred. Strange. 

But now it should work as expected – master and develop branch. Thanks again for reporting.
