### ISSUE TITLE
There is also another plugin with the same name

### ISSUE THREAD

**Issue by janstieler** [flokosiol/kirby-translations#6]
Hi,

could you think about a plugin namechange?
There are another Kirby plugin with the same name and for your plugin it would also work with teh name kirby-translationcheck or something else.

Cheers

**Comment by flokosiol** [comment]
Do you mean https://github.com/rasteiner/kirbytranslations? This plugin uses "static-translations" as folder name (see [forum topic](https://forum.getkirby.com/t/translations-edit-the-static-text-translations-of-your-site-in-your-panel/5626/7?u=flokosiol)). There should be no problem with using both plugins, I think.
