### ISSUE TITLE
Does this work with Kirby Tabs?

### ISSUE THREAD

**Issue by daybugging** [flokosiol/kirby-translations#8]
Just wondering if you have any experience so far regarding [Kirby-Tabs](https://github.com/afbora/Kirby-Tabs-Field) .. great plugin, thanks!

// Tested it, works great.

**Comment by flokosiol** [comment]
As you said, it works great with the Tabs plugin. 

You can place it inside a tab or (as I like to do) above the first tab to keep it visible no matter which tab is activated.
