### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by daybugging** [flokosiol/kirby-translations#9]
Hey there.
Maybe the mistake is on myself, but here goes: I want to include only translated pages in my menu, and the name of my 'type: translations' field is `translation_ready`. So my menu items I generate like this:

```php
  <?php foreach($pages->visible()->filterBy('translation_ready', '1') as $item) : ?>
    <li>
      <!-- code -->
    </li>
  <?php endforeach ?>
```

But, when there's no `.txt` content file, it seems to default to 1 (true) rather anything else. To make this work, I have to uncheck "translation is up-to-date" and save the page (even though it's not translated yet, destroying the whole point of actually not being translated).

Help! 🔨

**Comment by flokosiol** [comment]
As far as I know this is Kirby default behaviour. If no translation `.txt` is available the value of the default language will be used. But I think you can filter your pages collection like this to get rid of untranslated ones:

```php
<?php 
  $translatedPages = $pages->visible()->filterBy('translation_ready', '1')->filter(function($p) {
    return $p->content(site()->language()->code())->exists();
  }); 
?>
```

And then …
```
<?php foreach($translatedPages as $item): ?>
  ...
<?php endforeach ?>

**Comment by S1SYPHOS** [comment]
That's a quite useful filter example, why not put it in the README.md!
